version: "3.9"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restapi
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8080:8080"
