server:
    port: 8080
spring:
    profiles:
        active: dev
springdoc:
    swagger-ui:
        use-root-path: false
application-version: ^project.version^
application-description: ^project.description^
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        password: mysecretpassword
        url: jdbc:postgresql://localhost:5432/restapi
        username: postgres
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            platform: postgres
---
spring:
    config:
        activate:
            on-profile: qa
    datasource:
        password: mysecretpassword
        url: jdbc:postgresql://localhost:5432/restapi_qa
        username: postgres
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            platform: postgres
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        password: mysecretpassword
        url: jdbc:postgresql://localhost:5432/restapi_prod
        username: postgres
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            platform: postgres